
// export const contactEmail = "support@soh.com";

export const routes = {
    welcomepage: "/",
    dashboardpage: "/dashboard",
    addcurrencypage: "/addcurrency",
    walletspage: "/wallets",
    historypage: "/history",
    settingspage: "/settings",
    currencypage: "/currency",
    accountsupportpage: "/accountsupport",
    account: "/dashboard/account",

    loginpage: "/login",
    //login2fa: "/account/login/2fa/",
    //signup: "/signup",
    forgotten: "/forgotten",
    logout: "/logout",

    transactions: "/transactions",
    placeholder: "/placeholder",
    privacypolicy: "/privacypolicy",
    getbip39: "/getbip39",
    language: "/language",
    loginhistory: "/loginhistory",
    myaddresses: "/myaddresses",
    myphonenumbers: "/myphonenumbers",
    notificationsettings: "/notificationsettings",
    persona: "/persona",
    priceplan: "/priceplan",
    securitysettings: "/securitysettings",
    swapoldxqr: "/swapoldxqr",
    termsandconditions: "/termsandconditions",
    twofactorauthentication: "/twofactorauthentication",
    referralprogram: "/referralprogram",
    contacts: "/contacts",
    qreditnft: "/qreditnft",
    qslp1: "/qslp1",
    createtokens: "/createtokens",
    tokenoftrust: "/tokenoftrust",
    viewcontact: "/viewcontact",
    viewcontactheader: "/viewcontactheader",
    register: "/register",
    loginhelp: "/loginhelp",
    contacthistory: "/contacthistory",
    twofactor: "/twofactor",
    security: "/security",
    phone: "/phone"
};